/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMcRouteImport } from './routes/admin/mc'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminProfitRouteImport } from './routes/admin/profit'
import { Route as AdminPurchasesRouteImport } from './routes/admin/purchases'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AdminMcCostsRouteImport } from './routes/admin/mc.costs'
import { Route as AdminMcExcelRouteImport } from './routes/admin/mc.excel'
import { Route as AdminMcInventoryRouteImport } from './routes/admin/mc.inventory'
import { Route as AdminMcMarketplaceRouteImport } from './routes/admin/mc.marketplace'
import { Route as AdminMcNotificationsRouteImport } from './routes/admin/mc.notifications'
import { Route as AdminMcOrdersRouteImport } from './routes/admin/mc.orders'
import { Route as AdminMcPricingRouteImport } from './routes/admin/mc.pricing'
import { Route as AdminMcProductsRouteImport } from './routes/admin/mc.products'
import { Route as AdminMcReportsRouteImport } from './routes/admin/mc.reports'
import { Route as AdminMcSalesRouteImport } from './routes/admin/mc.sales'
import { Route as AdminMcSettingsRouteImport } from './routes/admin/mc.settings'
import { Route as AdminMcUsersRouteImport } from './routes/admin/mc.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMcRoute = AdminMcRouteImport.update({
  id: '/mc',
  path: '/mc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfitRoute = AdminProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AdminMcCostsRoute = AdminMcCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcExcelRoute = AdminMcExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcInventoryRoute = AdminMcInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcMarketplaceRoute = AdminMcMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcNotificationsRoute = AdminMcNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcOrdersRoute = AdminMcOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcPricingRoute = AdminMcPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcProductsRoute = AdminMcProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcReportsRoute = AdminMcReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcSalesRoute = AdminMcSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcSettingsRoute = AdminMcSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminMcRoute,
} as any)
const AdminMcUsersRoute = AdminMcUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminMcRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mc': typeof AdminMcRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit': typeof AdminProfitRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/mc/costs': typeof AdminMcCostsRoute
  '/admin/mc/excel': typeof AdminMcExcelRoute
  '/admin/mc/inventory': typeof AdminMcInventoryRoute
  '/admin/mc/marketplace': typeof AdminMcMarketplaceRoute
  '/admin/mc/notifications': typeof AdminMcNotificationsRoute
  '/admin/mc/orders': typeof AdminMcOrdersRoute
  '/admin/mc/pricing': typeof AdminMcPricingRoute
  '/admin/mc/products': typeof AdminMcProductsRoute
  '/admin/mc/reports': typeof AdminMcReportsRoute
  '/admin/mc/sales': typeof AdminMcSalesRoute
  '/admin/mc/settings': typeof AdminMcSettingsRoute
  '/admin/mc/users': typeof AdminMcUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mc': typeof AdminMcRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit': typeof AdminProfitRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/mc/costs': typeof AdminMcCostsRoute
  '/admin/mc/excel': typeof AdminMcExcelRoute
  '/admin/mc/inventory': typeof AdminMcInventoryRoute
  '/admin/mc/marketplace': typeof AdminMcMarketplaceRoute
  '/admin/mc/notifications': typeof AdminMcNotificationsRoute
  '/admin/mc/orders': typeof AdminMcOrdersRoute
  '/admin/mc/pricing': typeof AdminMcPricingRoute
  '/admin/mc/products': typeof AdminMcProductsRoute
  '/admin/mc/reports': typeof AdminMcReportsRoute
  '/admin/mc/sales': typeof AdminMcSalesRoute
  '/admin/mc/settings': typeof AdminMcSettingsRoute
  '/admin/mc/users': typeof AdminMcUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mc': typeof AdminMcRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit': typeof AdminProfitRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/mc/costs': typeof AdminMcCostsRoute
  '/admin/mc/excel': typeof AdminMcExcelRoute
  '/admin/mc/inventory': typeof AdminMcInventoryRoute
  '/admin/mc/marketplace': typeof AdminMcMarketplaceRoute
  '/admin/mc/notifications': typeof AdminMcNotificationsRoute
  '/admin/mc/orders': typeof AdminMcOrdersRoute
  '/admin/mc/pricing': typeof AdminMcPricingRoute
  '/admin/mc/products': typeof AdminMcProductsRoute
  '/admin/mc/reports': typeof AdminMcReportsRoute
  '/admin/mc/sales': typeof AdminMcSalesRoute
  '/admin/mc/settings': typeof AdminMcSettingsRoute
  '/admin/mc/users': typeof AdminMcUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/search'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/mc'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/profit'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/orders/$id'
    | '/admin/mc/costs'
    | '/admin/mc/excel'
    | '/admin/mc/inventory'
    | '/admin/mc/marketplace'
    | '/admin/mc/notifications'
    | '/admin/mc/orders'
    | '/admin/mc/pricing'
    | '/admin/mc/products'
    | '/admin/mc/reports'
    | '/admin/mc/sales'
    | '/admin/mc/settings'
    | '/admin/mc/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/search'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/mc'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/profit'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin'
    | '/orders/$id'
    | '/admin/mc/costs'
    | '/admin/mc/excel'
    | '/admin/mc/inventory'
    | '/admin/mc/marketplace'
    | '/admin/mc/notifications'
    | '/admin/mc/orders'
    | '/admin/mc/pricing'
    | '/admin/mc/products'
    | '/admin/mc/reports'
    | '/admin/mc/sales'
    | '/admin/mc/settings'
    | '/admin/mc/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/search'
    | '/_authenticated/addresses'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/wishlist'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/mc'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/profit'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/_authenticated/orders/$id'
    | '/admin/mc/costs'
    | '/admin/mc/excel'
    | '/admin/mc/inventory'
    | '/admin/mc/marketplace'
    | '/admin/mc/notifications'
    | '/admin/mc/orders'
    | '/admin/mc/pricing'
    | '/admin/mc/products'
    | '/admin/mc/reports'
    | '/admin/mc/sales'
    | '/admin/mc/settings'
    | '/admin/mc/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mc': {
      id: '/admin/mc'
      path: '/mc'
      fullPath: '/admin/mc'
      preLoaderRoute: typeof AdminMcRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profit': {
      id: '/admin/profit'
      path: '/profit'
      fullPath: '/admin/profit'
      preLoaderRoute: typeof AdminProfitRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/admin/mc/costs': {
      id: '/admin/mc/costs'
      path: '/costs'
      fullPath: '/admin/mc/costs'
      preLoaderRoute: typeof AdminMcCostsRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/excel': {
      id: '/admin/mc/excel'
      path: '/excel'
      fullPath: '/admin/mc/excel'
      preLoaderRoute: typeof AdminMcExcelRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/inventory': {
      id: '/admin/mc/inventory'
      path: '/inventory'
      fullPath: '/admin/mc/inventory'
      preLoaderRoute: typeof AdminMcInventoryRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/marketplace': {
      id: '/admin/mc/marketplace'
      path: '/marketplace'
      fullPath: '/admin/mc/marketplace'
      preLoaderRoute: typeof AdminMcMarketplaceRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/notifications': {
      id: '/admin/mc/notifications'
      path: '/notifications'
      fullPath: '/admin/mc/notifications'
      preLoaderRoute: typeof AdminMcNotificationsRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/orders': {
      id: '/admin/mc/orders'
      path: '/orders'
      fullPath: '/admin/mc/orders'
      preLoaderRoute: typeof AdminMcOrdersRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/pricing': {
      id: '/admin/mc/pricing'
      path: '/pricing'
      fullPath: '/admin/mc/pricing'
      preLoaderRoute: typeof AdminMcPricingRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/products': {
      id: '/admin/mc/products'
      path: '/products'
      fullPath: '/admin/mc/products'
      preLoaderRoute: typeof AdminMcProductsRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/reports': {
      id: '/admin/mc/reports'
      path: '/reports'
      fullPath: '/admin/mc/reports'
      preLoaderRoute: typeof AdminMcReportsRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/sales': {
      id: '/admin/mc/sales'
      path: '/sales'
      fullPath: '/admin/mc/sales'
      preLoaderRoute: typeof AdminMcSalesRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/settings': {
      id: '/admin/mc/settings'
      path: '/settings'
      fullPath: '/admin/mc/settings'
      preLoaderRoute: typeof AdminMcSettingsRouteImport
      parentRoute: typeof AdminMcRoute
    }
    '/admin/mc/users': {
      id: '/admin/mc/users'
      path: '/users'
      fullPath: '/admin/mc/users'
      preLoaderRoute: typeof AdminMcUsersRouteImport
      parentRoute: typeof AdminMcRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminMcRouteChildren {
  AdminMcCostsRoute: typeof AdminMcCostsRoute
  AdminMcExcelRoute: typeof AdminMcExcelRoute
  AdminMcInventoryRoute: typeof AdminMcInventoryRoute
  AdminMcMarketplaceRoute: typeof AdminMcMarketplaceRoute
  AdminMcNotificationsRoute: typeof AdminMcNotificationsRoute
  AdminMcOrdersRoute: typeof AdminMcOrdersRoute
  AdminMcPricingRoute: typeof AdminMcPricingRoute
  AdminMcProductsRoute: typeof AdminMcProductsRoute
  AdminMcReportsRoute: typeof AdminMcReportsRoute
  AdminMcSalesRoute: typeof AdminMcSalesRoute
  AdminMcSettingsRoute: typeof AdminMcSettingsRoute
  AdminMcUsersRoute: typeof AdminMcUsersRoute
}

const AdminMcRouteChildren: AdminMcRouteChildren = {
  AdminMcCostsRoute: AdminMcCostsRoute,
  AdminMcExcelRoute: AdminMcExcelRoute,
  AdminMcInventoryRoute: AdminMcInventoryRoute,
  AdminMcMarketplaceRoute: AdminMcMarketplaceRoute,
  AdminMcNotificationsRoute: AdminMcNotificationsRoute,
  AdminMcOrdersRoute: AdminMcOrdersRoute,
  AdminMcPricingRoute: AdminMcPricingRoute,
  AdminMcProductsRoute: AdminMcProductsRoute,
  AdminMcReportsRoute: AdminMcReportsRoute,
  AdminMcSalesRoute: AdminMcSalesRoute,
  AdminMcSettingsRoute: AdminMcSettingsRoute,
  AdminMcUsersRoute: AdminMcUsersRoute,
}

const AdminMcRouteWithChildren =
  AdminMcRoute._addFileChildren(AdminMcRouteChildren)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMcRoute: typeof AdminMcRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfitRoute: typeof AdminProfitRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMcRoute: AdminMcRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPosRoute: AdminPosRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfitRoute: AdminProfitRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
